version: '3.8'
services:
  api-gateway:
    build:
      context: ./backend/services/core-trading/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SAMRDDHI_ENV=dev
    networks: [samrddhi-network]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws
      - REACT_APP_USE_MOCK_DATA=true
    depends_on: [api-gateway]
    networks: [samrddhi-network]
networks:
  samrddhi-network:
    driver: bridge
    name: samrddhi-network
