[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.11
check_untyped_defs = false
ignore_missing_imports = true

[tool.flake8]
max-line-length = 100
exclude = .git,__pycache__,docs,venv
