name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Run frontend lint
        run: |
          cd frontend
          npx eslint "src/**/*.{ts,tsx}" || true

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy pytest

      - name: Run Python format/checks
        run: |
          black --check . || true
          isort --check-only . || true
          flake8 || true
          mypy || true

      - name: Run tests
        run: |
          pytest -q || true
